// === SHARED CONSTANTS ===
export const PERSONAL_INFO = {
  firstName: 'Piotr',
  lastName: 'Fraszczak',
  image: '/images/author.png',
} as const;

export const SOCIAL_LINKS = {
  linkedin: 'https://www.linkedin.com/in/12071995',
  github: 'https://github.com/Fraszczak',
  twitter: 'https://x.com/PPFraszczak',
  instagram: 'https://www.instagram.com/fraszczakp',
} as const;

// === SKILLS CONFIGURATION ===
export const SKILLS_CONFIG = [
  {
    id: 'html',
    orbitRadius: 100,
    size: 60,
    speed: 0.3,
    iconType: 'html' as const,
    phaseShift: 0,
    glowColor: 'cyan' as const,
    labelKey: 'skills.html',
  },
  {
    id: 'css',
    orbitRadius: 100,
    size: 50,
    speed: 0.4,
    iconType: 'css' as const,
    phaseShift: (2 * Math.PI) / 3,
    glowColor: 'cyan' as const,
    labelKey: 'skills.css',
  },
  {
    id: 'javascript',
    orbitRadius: 100,
    size: 50,
    speed: 0.4,
    iconType: 'javascript' as const,
    phaseShift: (4 * Math.PI) / 3,
    glowColor: 'cyan' as const,
    labelKey: 'skills.javascript',
  },
  {
    id: 'react',
    orbitRadius: 180,
    size: 40,
    speed: -0.3,
    iconType: 'react' as const,
    phaseShift: 0,
    glowColor: 'purple' as const,
    labelKey: 'skills.react',
  },
  {
    id: 'node',
    orbitRadius: 180,
    size: 40,
    speed: -0.3,
    iconType: 'node' as const,
    phaseShift: (2 * Math.PI) / 3,
    glowColor: 'purple' as const,
    labelKey: 'skills.node',
  },
  {
    id: 'tailwind',
    orbitRadius: 180,
    size: 60,
    speed: -0.3,
    iconType: 'tailwind' as const,
    phaseShift: (4 * Math.PI) / 3,
    glowColor: 'purple' as const,
    labelKey: 'skills.tailwind',
  },
  {
    id: 'angular',
    orbitRadius: 120,
    size: 60,
    speed: 0.7,
    iconType: 'angular',
    phaseShift: 0,
    glowColor: 'red',
    labelKey: 'skills.angular',
  },
  {
    id: 'typescript',
    orbitRadius: 150,
    size: 45,
    speed: -0.8,
    iconType: 'typescript',
    phaseShift: 45,
    glowColor: 'blue',
    labelKey: 'skills.typescript',
  },
  {
    id: 'dotnet',
    orbitRadius: 180,
    size: 40,
    speed: 0.7,
    iconType: 'dotnet',
    phaseShift: 90,
    glowColor: 'purple',
    labelKey: 'skills.dotnet',
  },
  {
    id: 'cypress',
    orbitRadius: 140,
    size: 40,
    speed: 0.8,
    iconType: 'cypress',
    phaseShift: 135,
    glowColor: 'green',
    labelKey: 'skills.cypress',
  },
  {
    id: 'azure',
    orbitRadius: 200,
    size: 40,
    speed: 0.5,
    iconType: 'azure',
    phaseShift: 180,
    glowColor: 'blue',
    labelKey: 'skills.azure',
  },
  {
    id: 'sql',
    orbitRadius: 160,
    size: 45,
    speed: 0.6,
    iconType: 'sql',
    phaseShift: 225,
    glowColor: 'teal',
    labelKey: 'skills.sql',
  },
  {
    id: 'jest',
    orbitRadius: 130,
    size: 45,
    speed: -0.6,
    iconType: 'jest',
    phaseShift: 270,
    glowColor: 'orange',
    labelKey: 'skills.jest',
  },
] as const;
